site_name: Vintage Reel Service Guides

nav:
  - Home: index.md
  - Penn 730 Service Guide: penn-730-service-guide.md
  - Initial Evaluation: initial-evaluation.md
  - Removing Line from and Adding Line to a Spool: removing-adding-line.md
  - Tools and Materials: tools-materials.md
  - Workspace Setup and Safety: workspace-setup-safety.md

theme:
  name: mkdocs






