site_name: Vintage Reel Service Guides
site_url: https://john-tech-writer.github.io/vintage-reel-service-guides

nav:
  - Home: index.md
  - Spinning Reels: docs/spinning-reels.md
  - Spincasting Reels: docs/spincasting-reels.md
  - Baitcasting Reels: docs/baitcasting-reels.md
  - Fly Reels: docs/fly-reels.md
  - Penn 720 Service Guide: penn/penn-720-service-guide.md
 
theme:
  name: readthedocs









