site_name: Vintage Reel Service Guides
site_url: https://john-tech-writer.github.io/vintage-reel-service-guides

nav:
  - Home: index.md
  - Penn 720 Service Guide: penn/penn-720-service-guide.md
  - Initial Evaluation: initial-evaluation.md
  - Removing Line from and Adding Line to a Spool: removing-adding-line.md
  - Tools and Materials: tools-materials.md
  - Workspace Setup and Safety: workspace-setup-safety.md

theme:
  name: readthedocs









